jobs:
  stage_0_job_0:
    name: mavros-msgs microstrain-inertial-msgs microstrain-inertial-driver
    runs-on: macos-11
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build ros-noetic-mavros-msgs ros-noetic-microstrain-inertial-msgs ros-noetic-microstrain-inertial-driver
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-noetic-mavros-msgs ros-noetic-microstrain-inertial-msgs
          ros-noetic-microstrain-inertial-driver
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
name: build_osx
on:
  push:
    branches:
    - buildbranch_osx
